#ifndef CONFIG_H_
#define CONFIG_H_

/* Chip8 Configuration */
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_MAX_DATA_REGISTERS 16
#define CHIP8_MAX_STACK_DEPTH 16
#define CHIP8_MAX_KEYS 16
#define CHIP8_DEFAULT_CHARSET_LOAD_ADDR 0x00
#define CHIP8_DEFAULT_CHARSET_BYTES 5
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define CHIP8_WINDOW_MULTIPLIER 10

/* Emulator window related settings */
#define EMULATOR_WINDOW_TITLE "Chip8 Emulator"
#define EMULATOR_WINDOW_WIDTH (CHIP8_WIDTH * CHIP8_WINDOW_MULTIPLIER)
#define EMULATOR_WINDOW_HEIGHT (CHIP8_HEIGHT * CHIP8_WINDOW_MULTIPLIER)
#endif